### ISSUE TITLE
Achat de votre site nettrader

### ISSUE THREAD

**Issue by Finamedia** [nicolas-f/nettrader#1]
Bonjour,

Je suis responsable de la société finamedia. Je souhaite vous faire une offre pour acheter votre nom de domaine nettrader.fr. Etes-vous ouvert à la vente de celui-ci?

Merci de votre attention.

Cordialement

**Comment by nicolas-f** [comment]
Bonjour,
Le nom de domaine n'est pas à vendre.
Cordialement,
